version: 0.0
os: linux

files:
  - source: server

    destination: /home/ec2-user/quickshop/server
  - source: frontend
    destination: /home/ec2-user/quickshop/my-app

hooks:

  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300

  AfterInstall:
    - location: scripts/install_server_deps.sh
      timeout: 300
    - location: scripts/install_frontend_deps.sh
      timeout: 300
    - location: scripts/build_frontend.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
