version: 0.0
os: linux

files:
  - source: server
    destination: /home/ec2-user/app/server
  - source: frontend
    destination: /home/ec2-user/app/frontend

hooks:
  # Останавливаем старый сервер перед копированием
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300

  # Копирование файлов происходит автоматически здесь

  # Устанавливаем зависимости и собираем фронтенд/бэкенд
  AfterInstall:
    - location: scripts/install_server_deps.sh
      timeout: 300
    - location: scripts/install_frontend_deps.sh
      timeout: 300
    - location: scripts/build_frontend.sh
      timeout: 300

  # Запускаем новый сервер
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
